# The app is deployed using service in render.com
# Change the host to https://fullstackopen-backends.onrender.com if we want to test it.

POST http://localhost:3001/api/persons
Content-Type:application/json

{
    "name": "Nguyen Le Minh",
    "number": "123-4567890"
}


###
# Get all persons

GET http://localhost:3001/api/persons


###
# Get one person, change the id
GET http://localhost:3001/api/persons/67660b794f8ce8c06104836d


###
# Change the id and name to an existing person

PUT http://localhost:3001/api/persons/67663e8f3800ee292cb9910e
Content-Type: application/json

{
    "name": "Nguyen Le Minh",
    "number": "987-65432"
}


###
# Delete person

DELETE http://localhost:3001/api/persons/4


###
GET http://localhost:3001/info
